### ISSUE TITLE
请教！

### ISSUE THREAD

**Issue by zhy958630** [JowayYoung/tinyimg-webpack-plugin#2]
你好，我想单独压缩一个文件夹的所有img或者png文件，而不是局限于有使用的图片，该怎么写webpack配置文件

**Comment by JowayYoung** [comment]
hello，因为webpack是处理那些互相依赖的文件，所以没有引用的图片就不会压缩，你可以使用我另一个开源nodejs工具来批量压缩图片，也是基于tinypng压缩的
项目地址：https://github.com/JowayYoung/img-master
img-master是一个多功能无限制的图像批处理工具，提供压缩、分组、标记和变换四大批处理功能，可以试下
