### ISSUE TITLE
打包后的图片资源没有被压缩，排查是写入资源方式的问题

### ISSUE THREAD

**Issue by liuxingyu521** [JowayYoung/tinyimg-webpack-plugin#4]
见下图 debugger 信息：
![image](https://user-images.githubusercontent.com/15321445/91417934-11ca0200-e884-11ea-9a34-ba58fb97ad2d.png)

ps. 针对这个问题有提 「[PR](https://github.com/JowayYoung/tinyimg-webpack-plugin/pull/3)」 修复哈

pps. 在公众号里看作者发表的文章「[嗯，手搓一个 TinyPng 压缩图片的 WebpackPlugin 也 SoEasy 啦](https://mp.weixin.qq.com/s/5LzXEb7d9-F8XB_LqyNYVg)」中看到这个插件，提供了压缩图片自动化的新思路，给作者点个赞 👍

**Comment by JowayYoung** [comment]
好的，谢谢指正

**Comment by JowayYoung** [comment]
合并了，谢谢大佬
